### ISSUE TITLE
more backslash will be added when pasting code 

### ISSUE THREAD

**Issue by hanye9895** [Tencent/cherry-markdown#25] opened 2021-11-16 11:54 UTC
![image](https://user-images.githubusercontent.com/68373171/141980206-f44eb951-85be-4238-8799-9f5f42fbb29c.png)

souce code：
```
```swift
print("hello")
let hello = """
	\\
	\\
	\\
	\\
	"""
```
and another ``` below

**Comment by jiawei686** [comment] 2021-11-16 12:53
Hi @hanye9895 

It's a bug caused by codeblock's inplement. We've solved it in #16 . And it's released in our lastest version 0.5.14

**Closed** 2021-11-19 05:19 UTC
